---
title: "Data Exploration"
author: "Gage Clawson"
date: "2/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## {.tabset .tabset-fade .tabset-pills}

###Initial data cleaning
```{r}
#Load packages
library(tidyverse)
library(tidyr)
library(RColorBrewer)
library(janitor)
library(chron)
library(sf)
library(leaflet)
library(tmap)
library(kableExtra)
library(ggplot2)
library(lubridate)


```


```{r}
#Load the data
oil_accidents_raw <- read_csv("raw_database.csv")
```

```{r}
# Initial data cleanup and wrangling

oil_accidents <- oil_accidents_raw %>%
  clean_names() %>% #clean the names snake case
  
  select(report_number, accident_year:liquid_type, accident_city:cause_category, net_loss_barrels:restart_date_time, property_damage_costs:all_costs) %>%  #select relevant columns
  separate(accident_date_time, c("month", "day", "year", "hour", "minute" ,"am_or_pm"), by = c("/", " ")) %>%  #separate the date time column
  
  unite("time", hour, minute, sep = ":") %>%  #bring time back together
  
  unite("time", time, am_or_pm, sep = " ") %>%  #bring time back together
  
  filter(accident_year != 2017) %>% #filter out the 2 2017 observations
  
  unite("date", year,month,day, sep = "-") %>% #make the date column again
  
  mutate(
         pipeline_type = case_when(
    is.na(pipeline_type) ~ "Not Specified",
    pipeline_type == pipeline_type ~ pipeline_type), 
    accident_city = case_when(
      pipeline_type == "Not Specified" & is.na(accident_city) ~ "Gulf of Mexico", 
      pipeline_type == "Not Specified" & !is.na(accident_city) ~ accident_city, 
      is.na(accident_city) & !is.na(accident_county) ~ accident_county,
      TRUE ~ accident_city))

#change date to date standard international date format. Chagne NA pipeline types to "Not Specified". Change those "Not Specified" without city names to "Gulf of Mexico" for city name. If there is a county name but not a city name, assign the city name as county name. 

# report number 20140310 is in mongolia... should be wyoming
# report number 20140063 is in china... should be in texas
# report number 20150309 is near portugal... should be new jersey. 
# these are obvious incidents of inputting data incorrectly. Lets filter to lat and long ranges for the united states. I think all of the latitudes look fine 

oil_accidents_US <- oil_accidents %>%
  filter(accident_longitude < -60) %>%
   filter(accident_longitude < -60) %>%
  mutate(liquid_type = case_when(
    liquid_type == "HVL OR OTHER FLAMMABLE OR TOXIC FLUID, GAS" ~ "Flammable or toxic fluid/gas", 
    liquid_type == "REFINED AND/OR PETROLEUM PRODUCT (NON-HVL), LIQUID" ~ "Refined Liquid Petroleum Product",
    liquid_type == "CRUDE OIL" ~ "Crude Oil", 
    liquid_type == "CO2 (CARBON DIOXIDE)" ~ "CO2 (Carbon Dioxide)",
    liquid_type == "BIOFUEL / ALTERNATIVE FUEL(INCLUDING ETHANOL BLENDS)" ~ "Biofuel",
    liquid_type == liquid_type ~ liquid_type
  ))

write.csv(oil_accidents_US, "cleaned_oil_data")
```


```{r}
 liquid_types <- oil_accidents_US %>%
      group_by(liquid_type, accident_state) %>%
      summarize(liquid_count = n())
    
    liquid_types$fraction = liquid_types$liquid_count / sum(liquid_types$liquid_count)
    liquid_types = liquid_types[order(liquid_types$fraction), ]
    liquid_types$ymax = cumsum(liquid_types$fraction)
    liquid_types$ymin = c(0, head(liquid_types$ymax, n=-1))
```


###Exploratory Maps 

```{r, include = FALSE}

#http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html 
#^link to information on how to make maps with r and how i figured this out

library(rworldmap)
library(mapdata)
library(maps)
library(ggmap)


usa <- map_data("usa")

#simple map
gg1 <- ggplot() +
  geom_polygon(data = usa, aes(x = long, y = lat, group = group), fill = "darkgreen", color = "red") +
  coord_fixed(1.3)  + 
  geom_point(data = oil_accidents_US, aes(x = accident_longitude, y= accident_latitude)) +
  theme_void()

gg1
```


```{r, include = FALSE}
library("rnaturalearth")
library("rnaturalearthdata")

#https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html
## make a geometry column out of the lat long columns to possibly use sf like we did in lab to map. 
oil_geom1 <- st_as_sf(oil_accidents_US, coords = c("accident_longitude", "accident_latitude"), 
    crs = 4326, agr = "constant") %>%
  select(accident_city, everything())

#make a world map layer
world <- ne_countries(scale = "medium", returnclass = "sf")

ggplot(data = world) +
    geom_sf() +
    geom_sf(data = oil_geom1, size = 1, shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-180, -65), ylim = c(19, 75), expand = FALSE) +
  theme_minimal()

```


```{r, include = FALSE}
#https://rstudio.github.io/leaflet/shapes.html
leaflet(oil_accidents_US) %>%
  addTiles()  %>% # Adds bg
  addCircles(lng = ~accident_longitude, lat = ~accident_latitude, weight = 1,
    radius = ~sqrt(all_costs)*30, popup = ~accident_city
  )


# these graphs make the same thing, for this one we don't have to provide the lat, long, since it is already provided in the "geometry" column
leaflet(oil_geom1) %>%
  addTiles()  %>% # Adds bg
 addCircles(weight = 1,
    radius = ~sqrt(all_costs)*30, popup = ~accident_city
  )


```

**BEST MAP**
```{r}
# interactive map. The hovering text that shows is whichever the first column in the data frame is. Not sure how to select it so it is not the first column. 
# Just looking through the map, there are some city names missing (NAs), some wrong city names... should we try to fix this? Not sure how. Maybe getting some lat long and city data and mergining? 
tmap_mode("view")
tm_basemap("Esri.NatGeoWorldMap") +
tm_shape(oil_geom1, projection = 2163) +
 tm_bubbles(size = "all_costs", alpha = 0.5,  col = "all_costs",  popup.vars = c("City: " = "accident_city", "Total Cost: " = "all_costs"), title.col = "Total Cost of Accident") +
  tm_view(view.legend.position = c("left", "bottom")) 
```

###GRAPHS

```{r}

# In the app we will change "CA" to the user selected state. 

top_cost_bystate_expl <- oil_accidents %>% 
      filter(accident_state == "AK") %>% 
      filter(accident_county != "NA") %>% 
      filter(operator_name != "NA") %>% 
      arrange(desc(all_costs)) %>% 
      head(10) %>% 
      arrange(all_costs) %>% 
      mutate(report_number = factor(report_number, levels = report_number)) 
      
state_length <- length(top_cost_bystate_expl$report_number)

top_cost_bystate_expl <- top_cost_bystate_expl %>% 
  mutate(rank = seq(from = state_length, to = 1, by = -1)) %>% 
  arrange(rank)

top_ten_cost_bystate <- oil_accidents %>% 
  filter(accident_state == "AK") %>% 
  arrange(desc(all_costs)) %>% 
  head(10) %>% 
  arrange(all_costs) %>% 
  mutate(report_number = factor(report_number, levels = report_number)) %>%
  ggplot(aes(x = report_number, y = all_costs/100000)) +
  geom_col(aes(fill = accident_county)) +
  theme_bw() +
  labs(x = "", y = "Total Cost of Accident ($100,000)")+
  coord_flip() +
  theme(legend.position = "right") +
  scale_x_discrete(expand = c(0,0), labels = rev(seq(1:10))) +
  scale_y_continuous(expand = c(0,0)) +
  guides(fill=guide_legend(title="Accident County"))

top_ten_cost_bystate

```


```{r}
library(treemap)

treemap_data <- oil_accidents_US %>%
  filter(accident_state != "NA") %>%
  group_by(accident_state, pipeline_type) %>%
  summarise(all_costs = sum(all_costs), net_loss_barrels = sum(net_loss_barrels)) %>%
  ungroup()

treemap(treemap_data, index = c("accident_state", "pipeline_type"), vSize = "net_loss_barrels", vColor = "pipeline_type", type = "categorical")

```

```{r}

liquid_types <- oil_accidents_US %>%
  filter(accident_state == "CA") %>%
  group_by(liquid_type, accident_state) %>%
  summarize(liquid_count = n())

liquid_types$fraction = liquid_types$liquid_count / sum(liquid_types$liquid_count)
liquid_types = liquid_types[order(liquid_types$fraction), ]
liquid_types$ymax = cumsum(liquid_types$fraction)
liquid_types$ymin = c(0, head(liquid_types$ymax, n=-1))

liquid_donut <- ggplot(liquid_types, aes(fill=liquid_type, ymax=ymax, ymin=ymin, xmax=4, xmin=3)) +
     geom_rect() +
     coord_polar(theta="y") +
     xlim(c(0, 4)) +
     theme(panel.grid=element_blank()) +
     theme(axis.text=element_blank()) +
     theme(axis.ticks=element_blank()) +
     annotate("text", x = 0, y = 0, label = NA) +
     labs(title="") +
    guides(fill=guide_legend(title="Liquid Type")) 


liquid_donut

```



